version: '3.0'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/app

    depends_on:
      - db


  db:
    image: mysql:5.7.16
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306

    volumes:
      - mysql-db:/var/lib/mysql


volumes:
  mysql-db: